Cogmasters/concord

core/io_poller.c
core/io_poller.h
src/adapter.c
src/client.c
src/gateway.c

Remove the requirement for calling the adapter in the main loop.
Hopefully this also fixes reconnect reason 4900 which was most likely caused by the ping not being sent immediately. If this is not the case, consider reducing ping interval from discord's recommended by 3000ms just to be safe.

Fix io poller

---

gencodecs/Makefile

Uses $(CC) instead of directly invoking GCC.

fix: makefiles use cc variable instead of gcc

---

include/discord-internal.h
src/client.c
src/gateway.c

Fix set_on_command

---

core/io_poller.c
core/io_poller.h
include/discord.h
src/discord-adapter.c
src/discord-client.c
src/discord-gateway.c

Changes all relate to io_poller
Added documentation, extra param `struct io_poller *io` to io_poller_callbacks and a new function discord_get_io_poller()
Eliminate the requirement for the user to have a separate thread when they want to poll their own file descriptors
simple example using stdin
```c
static void
on_stdin(struct io_poller *io, enum io_poller_events events, void *data) {
struct discord *client = data;
char buf[4096];
int n = read(STDIN_FILENO, buf, sizeof buf);
write(STDOUT_FILENO, buf, n);
}
int
main(void) {
struct discord *client = discord_config_init("config.json");
struct io_poller *io = discord_get_io_poller(client);
io_poller_socket_add(io, STDIN_FILENO, IO_POLLER_IN, on_stdin, client);
discord_run(client);
}
```

io_poller docs, and features.

---

core/websockets.h

fix: Minor English Syntax errors in websockets.h comments -- No code functionality impact
Clarify intent of 2 constants

fix: English syntax in comments for websockets.h

---

examples/audit-log.c
include/concord-once.h
include/discord-internal.h
src/concord-once.c
src/discord-client.c
test/async.c

Disconnect client(s) from their on-going session if a `SIGINT` is received.
* Abruptly ending the program means Discord would never be notified of the client's disconnect, thus keeping a lingering `online` status until it fails to receive a heartbeat payload.
* Ensure full cleanup of the API resources so that users may catch up their memory leaks, or incorrect cleanup from concord's side.
A `ccord_has_sigint` global is set once a SIGINT is detected, which will be checked against by all running clients and they will be prompted to call `discord_shutdown()`. 
Removed now outdated `test/async.c` logic that had a custom SIGINT handler for gracefully disconnecting, with this PR `Ctrl`+`C` for a clean disconnect still works just fine.
I haven't added any mutexes around the `ccord_has_sigint` …

Client disconnect on SIGINT

---

Makefile
cog-utils/cog-utils.c
cog-utils/cog-utils.h
core/third-party/priority_queue.c
core/third-party/priority_queue.h
examples/Makefile
examples/timers.c
include/discord-internal.h
include/discord.h
licenses/LICENSE.priority_queue
src/discord-client.c
src/discord-timer.c

Added a Priority Queue
Added Timer Support
The gateway, adapter, and user of the library should be able to schedule events at any point in the future
Timer using a minheap binary tree priority queue

Add Timer Support

---

src/discord-client.c

reverse improper comparison operators which were causing a busy loop by setting poll_time to 0 every time

fix(discord-client): timer causing busy loop

---

include/discord-internal.h
include/discord.h
src/discord-client.c
src/discord-timer.c

Allow Timer to modify itself via discord_timer_ctl in the callback
Added internal timer functionality
Converted wakeup timer to a real timer using the internal timer
on_wakeup seems to still work the same, was also used to test DISCORD_TIMERS_DONT_UPDATE

Timer Updates

---

cog-utils/chash.h
cog-utils/logconf.c
include/discord-internal.h
src/discord-adapter.c
src/discord-adapter_ratelimit.c
src/discord-client.c

Create a `struct discord_ratelimiter` datatype to encompass all ratelimiting related data, and replace hard to read dependencies (uthash.h).
1. Reorganize and modularize `discord-adapter_ratelimit.c`
2. Replace uthash.h with chash.h
Improve comprehension and readability.

Ratelimiting refactor

---

src/Makefile

This pull request fixes a bug where `Makefile` would not compile the `oauth2` module in `src` directory when the `make` command is invoked.
```console
$ uname -srvmpio
Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
1. Clone this repository and install the latest development version
```console 
$ git clone https://github.com/Cogmasters/concord && cd concord
$ git checkout dev 
$ make -j`nproc`
$ sudo make install
```
2. Build a small bot example that uses `discord_get_current_bot_application_information()`
```c
#include <string.h>
#include <concord/discord.h>
#include <concord/log.h>
#include <pthread.h>
#define CONFIG_PATH "res/config.json"
void on_complete(
struct discord *client, 
struct discord_response *resp, 
const struct …
```

Fix `Makefile` not compiling the `oauth2` module

---

core/io_poller.c
include/discord-internal.h
src/discord-client.c
src/discord-rest.c
src/discord-timer.c

Make the discord_timer api thread safe.
Any thread should be able to call discord_timer(...) and have it run the callback on the main thread
Using a non-recursive mutex, a conditionals, and io_poller to wake up the thread
Stress tested with many threads simultaneously creating 1000s of timers, and using valgrind to ensure no memory leaks.

Threadsafe Timers

---

include/discord-internal.h
src/discord-gateway.c

Discord will be using a different URL for resuming purposes, this commit
implements that
Use Discord `resume gateway url` for session resuming
In the future it is expected this URL to be used for resuming session purposes
The URL is parsed and kept internally, and the client should attempt to reconnect to that URL if it wants to resume to the previous session.
The client has been shutdown without sending a WebSockets `CLOSE` opcode to Discord, and then managed to resume to the ongoing session.

Use resume gateway url for session resuming

---

gencodecs/.gitignore
gencodecs/api/application.PRE.h
gencodecs/api/application_commands.PRE.h
gencodecs/api/audit_log.PRE.h
gencodecs/api/auto_moderation.PRE.h
gencodecs/api/channel.PRE.h
gencodecs/api/custom.PRE.h
gencodecs/api/emoji.PRE.h
gencodecs/api/gateway.PRE.h
gencodecs/api/guild.PRE.h
gencodecs/api/guild_scheduled_event.PRE.h
gencodecs/api/guild_template.PRE.h
gencodecs/api/interactions.PRE.h
gencodecs/api/invite.PRE.h
gencodecs/api/message_components.PRE.h
gencodecs/api/oauth2.PRE.h
gencodecs/api/permissions.PRE.h
gencodecs/api/stage_instance.PRE.h
gencodecs/api/sticker.PRE.h
gencodecs/api/teams.PRE.h
gencodecs/api/user.PRE.h
gencodecs/api/voice.PRE.h
gencodecs/api/voice_connections.PRE.h
gencodecs/api/webhook.PRE.h
gencodecs/gencodecs-process.PRE.h

Improve readability of gencodecs
As anything that relies exclusively on the C preprocessor, Gencodecs is a bit hard to follow, this PR aims to enforce some "rules" to the gencodecs syntax to make its comprehension easier
Add an env variable `GENCODECS_RECIPE` that keeps track of which generating recipe is currently being processed
Concord successfully generates its datatypes and compiles

Gencodecs refactor

---

include/discord-internal.h
include/discord.h
src/discord-client.c
src/discord-refcount.c
src/discord-rest_request.c

discord_claim() now allows multiple claims to the same resource (instead of a single one), so it only gets cleaned up after the same amount of discord_unclaim() has been called.
Add this change to make caching easier to implement and not require cloning every resource it references.

Reference-counter allows N claims to the same resource

---

gencodecs/api/channel.PRE.h
gencodecs/api/custom.PRE.h
gencodecs/api/guild.PRE.h
gencodecs/api/teams.PRE.h

Make every bitmask field a `u64bitmask`
Some bitmask fields vary between being a string and a u64bitmask type, which makes it inconsistent to the user
Changes the `gencodecs` specs to replace each bitmask string with a u64bitmask
Simply compiling the codebase should be enough to tell if this change was successful
Although this is a small change, it's also a breaking change. Any existing bots using the string bitmasks will need to be updated.

Type inconsistency for bitmasks

---

examples/timers.c
include/discord-internal.h
include/discord.h
src/discord-gateway_dispatch.c
src/discord-loop.c
src/discord-rest_ratelimit.c
src/discord-timer.c

- Added DISCORD_TIMER_TICK flag for on_tick callback
- Replaced single callback with 2 separate callbacks(on_tick, and on_status_changed)
when a timer is run, `on_tick` will be called with the flag `DISCORD_TIMER_TICK` set
when a timer is deleted, `on_status_changed` will be called with the flag `DISCORD_TIMER_DELETE` set
when a timer is canceled, `on_status_changed` will be called with the flag `DISCORD_TIMER_CANCELED` set
- Updated timer example
Before:
```c
static void
on_timer_tick(struct discord *client, struct discord_timer *timer) {
if (!(timer->flags & DISCORD_TIMER_CANCELED)) {
// do something
}
// clean up resources
}
discord_timer(client, on_timer_tick, NULL, 0);
```
Now:
```c
static void
on_timer_tick(struct discord *client, struct discord_timer *timer) {
// do something
// …
```

Timer Callback Refactor

---

core/anomap.c
core/anomap.h
examples/Makefile
examples/cache.c
include/discord-cache.h
include/discord-internal.h
include/discord.h
src/Makefile
src/discord-cache.c
src/discord-client.c
src/discord-events.c
src/discord-gateway.c
src/discord-gateway_dispatch.c

- Create an extendable caching interface
- Implement caching for Guilds and Messages(more to come later)
```c
// to enable caching
discord_cache_enable(client, DISCORD_CACHE_MESSAGES | DISCORD_CACHE_GUILDS);
// get item from cache
const struct discord_guild *guild = discord_cache_get_guild(client, guild_id);
if (guild) {
printf("guild name '%s'\n", guild->name);
discord_unclaim(client, guild); // MUST ALWAYS UNCLAIM CACHED RESOURCES
}
```
_more detailed example can be seen in examples/cache.c_
- Avoid having to make REST request for commonly used data
- Skip having to use a callback to request local data
- Have gateway dispatch all callbacks to caching handler before calling user callback
Testing using examples/cache.c and confirmed it's all working fine, garbage collector is being run, …

Caching Interface

---

src/discord-rest_ratelimit.c

This PR will fix an overread in `src/discord-rest_ratelimit.c`
Copying of too many bytes from a string.
This PR will change the `RATELIMITER_TABLE_INIT` macro to use `strlen` to determine the length of the string `_key` passed to it.
Compiles and runs the "guild" and "ping-pong" examples flawlessly with AddressSanitizer.

 Fix RATELIMITER_TABLE_INIT reading too many bytes from the string given.

---

Doxyfile
core/error.h
include/discord.h
src/discord-rest_request.c

- Add positive integer CCORDcode reserved for change of states
- Update `@CCORD_return` Doxygen alias with new description
Sometimes, when dealing with asynchronous operations it is too early to tell whether it was successful or not. The positive integers may so be used for signaling a change of state, and that an operation is underway.
For now, added `CCORD_PENDING`, which is returned for asynchronous requests that have just been enqueued.
Example bots work just fine, as this was a simple swap of returned values.

Reserve positive integer values of CCORDcode for change of states

---

include/discord-internal.h
src/discord-rest_ratelimit.c
src/discord-rest_request.c

Closes #83, closes #84
- Use the 429 `retry_after` value for freezing up the request's bucket
- `HTTP_POST` and `HTTP_MIMEPOST` being used in the same endpoint should generate the same bucket key
- _discord_request_retry() would return true even if the request wasn't added back to the bucket's queue, resulting in a bucket freeze, making so consecutive requests of that bucket group never reach Discord
- They should be considered identical values when generating a bucket's key
- `bucket->busy_req` must be set to NULL once a 429 has been detected, and the failed request should be added back to the head of its queue. This will make it so that the next time the bucket is checked, it will trigger a timeout based on the `retry_after` value.
See #83 example code

Fix ratelimiting 429 and bucket creation

---

core/carray.h
gencodecs/api/channel.PRE.h
include/discord-request.h
src/channel.c
src/discord-rest_request.c
src/interaction.c
src/webhook.c

Closes #78 
Allow for multiple attachments in a single request
Prior to this in order to send multiple attachments in a single message, the user would have to manually assign each individual attachment an ID, which was very unintuitive.
Automatically initializes each individual attachment ID, when an attachments field is included by the user.
Ran it against the example code from #78

Fix sending multiple attachments in a message

---

include/osname.h

- [yes] I *understand* the code that I have edited, and have the means
This PR adds
- comments to osname.h
- more supported OSes
osname.h seems to be relatively confusing to newcomers with its long and complex code, uninterrupted by any comments telling you what's going on.
This adds all of the comments such that you can see what is going on.
Almost all of these have been tested except for MPE, ConvexOS, OS-9, Aegis, and a few others that I physically don't have to run this on. 
Some people seem to be confused as to how this actually works. This ought to fix that.

feat: comments explaining osname.h, and more detectable OSes

---

docs/guides/compiling_on_windows.md
docs/guides/concord_on_old_systems.md
docs/guides/msys2_and_mingw64.md

This PR improves the documentation situation of the project, especially when it comes to some of the more exotic platforms that Concord has been ran on in the past.
Concord is in dire need of guides.
The instructions mentioned in the "weird platforms" guide has been tested on Solaris 10 with Sun Studio 11; the others were either partially tested (HP-UX) or successful (AIX, z/OS)
These will eventually need to be thrown onto the GitHub Pages system.

Several additional guides and a documentation overhaul

---

docs/guides/debugging.md

Adding the debugging guide, requested in this [issue](https://github.com/Cogmasters/concord/issues/109).
Because it was requested.
No testing, but some of the grammar was reviewed with grammarly.

docs(guide): add debugging guide

---

docs/guides/setup_concord_with_env.md

Adding the "Setting up with `env` variables" guide.
Because it was requested on issue [109](https://github.com/Cogmasters/concord/issues/109).

docs(guide): add env guide

---

docs/guides/installing_concord_termux.md

This PR adds the guide of how to install (compile) Concord on Termux.
Because there is no documentation of how to do it.
The codes (commands) have been tested on a device with fresh OS.

docs(guide): add installing on termux guide

---

src/discord-gateway.c
src/interaction.c

Adjusted `buf` in `discord_create_interaction_response()` to be the size of 16384 like the others.

Buffer for interaction response too small

---

include/concord-once.h
src/concord-once.c
src/discord-loop.c

Currently, if users attempt to compel concord to exit, e.g. using discord_shutdown, this will result in thread unsafe operations that can lead to a segfault.
This allows users to safely cause concord to exit, leveraging the existing flag used for SIGINT handling.
Fixes #135
- [X ] I *understand* the code that I have edited, and have the means
This allows for multithread safe shutdowns, using the same functionality that the SIGINT handler uses.
Prevents segfaults on shutdown.
Uses the same functionality as SIGINT handler.
Tested locally and successfully prevents segfaults. Users can call pthread_join on any client threads and they will exit momentarily on their own, cleanly.

fix: allow async client shutdowns for multithreading safety.

---

core/websockets.c

This PR comes with edits that should fix the issue that when TLS ends for some reasons, will proceed to close connection.
Since the connection is already closed, will proceed to only end connection without trying to close.
Changes were not tested, should be done soon. But is successfully compiling.

fix(websockets): fix tls related bug

---

.gitignore
core/attributes.h
core/cog-utils.h
core/logconf.h
core/queriec.h
core/user-agent.c
include/discord-internal.h
src/channel.c
src/guild.c
src/guild_scheduled_event.c
src/interaction.c
src/webhook.c

This code adds fixes for bugs caused on [this PR](https://github.com/Cogmasters/concord/pull/136) (and fix for missing % on other places), and adds compile-time checks (GCC) for not causing this anymore.
By adding `__attribute__((format(printf, x, y)));` at function definitions inside a #if to check if compiler supports it.

Removed extra %s & added compile-time check

---

README.md

This pull request fixes the broken links in 'Build Instructions' section of README.md.

docs(README.md): fix broken links in 'Build Instructions' section

---

README.md

This pull request fixes a typo in 'Build Instructions' section of README.md.
I believe root privilege is required to install packages via `pkg`.
```console
jdeokkim@freebsd:~ % pkg install curl
pkg: Insufficient privileges to install packages
```

docs(README.md): fix a typo in 'Build Instructions' section

---

core/websockets.c
src/discord-client.c
src/discord-gateway.c
src/discord-loop.c

This PR fixes an fatal issue that would block Concord from reconnecting to the gateway.
To allow bots to run for a long time, not being disconnecting without reconnecting.
This includes various fixes about connections, both TLS and 1000 WS status code.
It was tested by persons on Cogmaster's Discord and verified that the fix is working, properly reconnecting when disconnected abruptly.

Fix permanent shutdowns (TLS & 1000 close code)

---

include/discord-internal.h
src/concord-once.c
src/discord-client.c
src/discord-loop.c

fixed concord-once to be thread-safe and signal-safe

fix(concord-once): make signal safe, and use a proper init counter

---

core/io_poller.c
core/websockets.c
src/discord-rest_request.c

This PR "replaces" (deprecated) [curl_multi_socket_all](https://curl.se/libcurl/c/curl_multi_socket.html) with [curl_multi_socket_action](https://curl.se/libcurl/c/curl_multi_socket_action.html).
As mentioned before, `_all` is deprecated since 7.19.5. In other words, versions above or equal 7.19.5 *should not* use it, and *should* use `_action` instead.  [Concord requires libcurl 7.56.1 minimum](https://github.com/Cogmasters/concord/blob/master/README.md?plain=1#L108), which makes its usage not recommended.
This PR introduces the usage of `curl_multi_socket_action` (as per "recommended" by libcurl documentation) together with `curl_multi_perform`, replacing `curl_multi_socket_all`.
To test the minimum "workability" of this PR, a bot was …

Fix cURL deprecated warning

---

src/discord-rest_request.c

This PR fixes a memory leak that happened when setting a `reason` field for requests.
This assures that memory won't increase over time.
By `free`ing on `discord_request_cancel` function.
Testing was done via a small bot that only has the function of deleting a message with a reason.

Fix memory leak when using `reason` field

---

include/discord-internal.h
src/discord-gateway.c
src/discord-gateway_dispatch.c

This PR introduces checks that ensures that the previous heartbeat was responded.
This avoids keeping a zombie connection, where the connection is over, however the client (Concord) is unaware of that for some reason. Heartbeats are meant for this, and should be used as it.
This introduces a `hbeat_answered` field, that defines whether or not the previous heartbeat was answered/responded. 
Basic testing was done. However better testing should be done, and the code should be reviewed as well.
While I believe it's important this PR, the reason for a lot of times Concord be unaware of closes may be to cws. I'll investigate further.

feat: zombie connection check

---

docs/guides/slash-commands.md

Adding the slash commands guide.
Because it was requested by issue #109.
The codes (code example) was tested and no warnings and errors were found.
Gramatical errors may be found.

docs(guide): add slash commands guide

---

.gitignore
Makefile
README.md
concord.pc

I made a concord.pc file for pkg-config. The makefile now installs (and uninstalls) it to /usr/share/pkgconfig/concord.pc. I also had to add it to the .gitignore.
I added this because, at least for me, it makes integrating concord with cmake a lot easier. I imagine that it might help some others as well.
I created a concord.pc file.
I have actually been using the pkg-config file for a month or two without issue. Just figured now that it might be helpful to others.

pkg-config support

---

core/websockets.c

Labels must be declared after declarations; this moves the label to avoid compilation failure.
Fixes #196
- [ X] I *understand* the code that I have edited, and have the means
Fix compilation error due to label declared before declarations

fix: Fix compilation failure due to label before declarations.

---

include/discord-internal.h
include/discord-response.h
src/discord-rest_request.c

Include raw JSON with done and fail callback response
Allow users to parse Discord errors in runtime, as described here:
https://discord.com/developers/docs/reference#error-messages
Include a new attribute `.json` under `struct discord_response` for `done` and `fail` callbacks
WIP

Include raw json with response

---

core/attributes.h
core/queriec.h
include/concord-once.h
src/concord-once.c

* Fixes the most of the warnings generated, and also some spots I noticed went over 80 characters.
* Note: We still need to fix the few depreciated Curl warnings.
* Another Note: ``(size_t)src->size`` is fine, and realistically the warning should not be there. (discord-rest_request.c:532)
* To stop the spam of warnings on most systems.
* To save lives.
* void arguments in prototypes.
* Checks the system for the correct castings with ioctl.
Ran the builds, and tested on a bot.
Let's rewrite concord in rugbust.

Fix: Unnecessary warnings
